# Generated by Django 5.0 on 2023-12-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=50)),
                ('note_description', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_notes',
            },
        ),
    ]
