# Generated by Django 5.0 on 2023-12-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='note_title',
            field=models.CharField(max_length=200),
        ),
    ]
