# Generated by Django 5.0 on 2024-01-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0002_alter_notemodel_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='status',
            field=models.CharField(default='not completed', max_length=100),
        ),
    ]
