# Generated by Django 5.0 on 2024-01-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0003_notemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
