# Generated by Django 5.0 on 2024-01-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0004_alter_notemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='status',
            field=models.CharField(default='not completed', max_length=100),
        ),
    ]
